// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAVrqSyIuaMhETRtllaZHSHBuw_U1tnzM',
    appId: '1:130128118754:web:edff15319fe86cc060afbb',
    messagingSenderId: '130128118754',
    projectId: 'cloud-message-abf61',
    authDomain: 'cloud-message-abf61.firebaseapp.com',
    storageBucket: 'cloud-message-abf61.firebasestorage.app',
    measurementId: 'G-0P1KC3NZQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7XSwD719d1eE2UoVCu0DhRlIfi3BLg4o',
    appId: '1:130128118754:android:656414bdd595d22960afbb',
    messagingSenderId: '130128118754',
    projectId: 'cloud-message-abf61',
    storageBucket: 'cloud-message-abf61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8AEKoc42X-z-5wIeeIe4tAI7_SU6lLI8',
    appId: '1:130128118754:ios:069de55dccf7c58f60afbb',
    messagingSenderId: '130128118754',
    projectId: 'cloud-message-abf61',
    storageBucket: 'cloud-message-abf61.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8AEKoc42X-z-5wIeeIe4tAI7_SU6lLI8',
    appId: '1:130128118754:ios:069de55dccf7c58f60afbb',
    messagingSenderId: '130128118754',
    projectId: 'cloud-message-abf61',
    storageBucket: 'cloud-message-abf61.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAVrqSyIuaMhETRtllaZHSHBuw_U1tnzM',
    appId: '1:130128118754:web:6642bbf6a638c63960afbb',
    messagingSenderId: '130128118754',
    projectId: 'cloud-message-abf61',
    authDomain: 'cloud-message-abf61.firebaseapp.com',
    storageBucket: 'cloud-message-abf61.firebasestorage.app',
    measurementId: 'G-3Z8C5PG8B7',
  );

}