// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpfxcvfevY2gyhlKElivIb4220lfYeu34',
    appId: '1:196110849791:web:9b1a6165878056f7741eca',
    messagingSenderId: '196110849791',
    projectId: 'notes-37e7e',
    authDomain: 'notes-37e7e.firebaseapp.com',
    storageBucket: 'notes-37e7e.firebasestorage.app',
    measurementId: 'G-YK89S510TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANIG9JKEb1jS2gCtOOyedTuRKbYnV9mno',
    appId: '1:196110849791:android:471dde4bef145e17741eca',
    messagingSenderId: '196110849791',
    projectId: 'notes-37e7e',
    storageBucket: 'notes-37e7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDORrfAppmlvumu0chGuJrSE12eRt2AzSA',
    appId: '1:196110849791:ios:23a3acd41b775be4741eca',
    messagingSenderId: '196110849791',
    projectId: 'notes-37e7e',
    storageBucket: 'notes-37e7e.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDORrfAppmlvumu0chGuJrSE12eRt2AzSA',
    appId: '1:196110849791:ios:23a3acd41b775be4741eca',
    messagingSenderId: '196110849791',
    projectId: 'notes-37e7e',
    storageBucket: 'notes-37e7e.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpfxcvfevY2gyhlKElivIb4220lfYeu34',
    appId: '1:196110849791:web:caf13aab79f20610741eca',
    messagingSenderId: '196110849791',
    projectId: 'notes-37e7e',
    authDomain: 'notes-37e7e.firebaseapp.com',
    storageBucket: 'notes-37e7e.firebasestorage.app',
    measurementId: 'G-1VHJRXY93T',
  );
}
