// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC50_ePqgNPMikOZvA-15nr5DQjVA3DJOw',
    appId: '1:1030286618097:web:9c2ac2ea6376862a266850',
    messagingSenderId: '1030286618097',
    projectId: 'daftarbelanja-db53c',
    authDomain: 'daftarbelanja-db53c.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-db53c-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-db53c.firebasestorage.app',
    measurementId: 'G-VLQRW9LQNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-OZUfFyw3RZoJsjrmteud8oe4Kh1AjsI',
    appId: '1:1030286618097:android:c40602caa1c2ad4b266850',
    messagingSenderId: '1030286618097',
    projectId: 'daftarbelanja-db53c',
    databaseURL: 'https://daftarbelanja-db53c-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-db53c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhpOgJxeIz0NL9k089QXUGais4e1HN_WM',
    appId: '1:1030286618097:ios:527f638e160fc2d5266850',
    messagingSenderId: '1030286618097',
    projectId: 'daftarbelanja-db53c',
    databaseURL: 'https://daftarbelanja-db53c-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-db53c.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhpOgJxeIz0NL9k089QXUGais4e1HN_WM',
    appId: '1:1030286618097:ios:527f638e160fc2d5266850',
    messagingSenderId: '1030286618097',
    projectId: 'daftarbelanja-db53c',
    databaseURL: 'https://daftarbelanja-db53c-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-db53c.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC50_ePqgNPMikOZvA-15nr5DQjVA3DJOw',
    appId: '1:1030286618097:web:9fd593c22fb60549266850',
    messagingSenderId: '1030286618097',
    projectId: 'daftarbelanja-db53c',
    authDomain: 'daftarbelanja-db53c.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-db53c-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-db53c.firebasestorage.app',
    measurementId: 'G-0N8H423E33',
  );
}
