// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAszpmPX5hhDv4-88iU3FJpLio1C7iAERQ',
    appId: '1:721282410393:web:51d3c637281421bd105508',
    messagingSenderId: '721282410393',
    projectId: 'mdpgold-9beb1',
    authDomain: 'mdpgold-9beb1.firebaseapp.com',
    databaseURL: 'https://mdpgold-9beb1-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-9beb1.firebasestorage.app',
    measurementId: 'G-RRSQKL13TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbqG6chDn_5Zbg85K5IZgc3R-MwD2mw7k',
    appId: '1:721282410393:android:94dd2269c070c1be105508',
    messagingSenderId: '721282410393',
    projectId: 'mdpgold-9beb1',
    databaseURL: 'https://mdpgold-9beb1-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-9beb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzRVGmveXo-WT4ZeYrikzBdQmwvACzcqc',
    appId: '1:721282410393:ios:e4b109e194e67df7105508',
    messagingSenderId: '721282410393',
    projectId: 'mdpgold-9beb1',
    databaseURL: 'https://mdpgold-9beb1-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-9beb1.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzRVGmveXo-WT4ZeYrikzBdQmwvACzcqc',
    appId: '1:721282410393:ios:e4b109e194e67df7105508',
    messagingSenderId: '721282410393',
    projectId: 'mdpgold-9beb1',
    databaseURL: 'https://mdpgold-9beb1-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-9beb1.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAszpmPX5hhDv4-88iU3FJpLio1C7iAERQ',
    appId: '1:721282410393:web:d9cff8e1ffee2cd8105508',
    messagingSenderId: '721282410393',
    projectId: 'mdpgold-9beb1',
    authDomain: 'mdpgold-9beb1.firebaseapp.com',
    databaseURL: 'https://mdpgold-9beb1-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-9beb1.firebasestorage.app',
    measurementId: 'G-Y2X8YDJ56F',
  );

}